### ISSUE TITLE
jdcal version peg

### ISSUE THREAD

**Issue by jsfenfen** [wsjdata/clinton-email-cruncher#3]
pip can't find me a version of jdcal 1.0 (using python 2.7.11). I assume a later version will work (1.2 is current). Is there any reason to think it _has_ to be 1.0 ?

**Comment by martinburch** [comment]
Hi, I think you're right. The requirements file was developed by doing `pip freeze` so it's not permissive at all. My development environment was Python 2.7.10.

I think `jdcal` module is a dependency for one of the modules that are actually required:
requests, requests_cache, certifi, peewee, slate and csvkit. slate _must_ have pdfminer==20110515

**Comment by martinburch** [comment]
@jsfenfen does this look ok to you now?

**Comment by martinburch** [comment]
Closing as resolved.
